version: "3.9"

services:
  db:
    image: postgres:15
    container_name: autoatendimento-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bcad200965
      POSTGRES_DB: autoatendimento
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - autoatendimento-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autoatendimento-app
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:Bcad200965@db/autoatendimento
    depends_on:
      - db
    command: ["/bin/sh", "-c", "sleep 30 && /wait-for-it.sh db:5432 -- uvicorn app.main:app --host 0.0.0.0 --port 8000"]
    networks:
      - autoatendimento-network

networks:
  autoatendimento-network:
    driver: bridge

volumes:
  db_data: